var Boot=99
var AnlagenKWP=4500
var time_start = new Array(8,7,6,6,6,6,6,6,7,7,8,8)
var time_end = new Array(17,18,20,21,21,22,22,21,20,19,17,17)
var sollMonth = new Array(2,6,9,11,11,13,13,12,10,6,4,3)
var SollYearKWP=850
var AnzahlWR = 1
var MaxWRP=new Array(AnzahlWR)
MaxWRP[0]=new Array(4500,30000,450000,3000000)
var WRInfo = new Array(AnzahlWR)
WRInfo[0]=new Array("SunnyBoy","         1",4500,0,"WR 1",1,null,null,0,null,2,0,1,1000,null)
var HPTitel="Photovoltaik"
var HPBetreiber="Gisela und Christof Warlich"
var HPEmail="christof@warlich.name"
var HPStandort="Haselhang 7"
var HPModul="RCA"
var HPWR="SMA SunnyBoy"
var HPLeistung="4,5kWp"
var HPInbetrieb="25.11.2004"
var HPAusricht="23° Süd"
var BannerZeile1="PV-Anlage"
var BannerZeile2="4,5kWp am Haselhang"
var BannerZeile3="im Netz seit November 2004"
var BannerLink="warlich.bplaced.net/Haselhang+"
var StatusCodes = new Array(AnzahlWR)
var FehlerCodes = new Array(AnzahlWR)
StatusCodes[0] = "Erst.Einsch.,Warte Spannung,Warte Ausschlt,Konstantspann.,MPP Low,MPP,Warten,Warten,Relaistest,Fehlersuchbetr,Übertemp.Absc,Leistungsbegr,Überlastabsch,Überspannab,Netzausfall,Nachtabschalt,Betriebshemm., ,AFI Abschalt.,Iso zu gering, , , , ,Fehler DSP,Test L-Elektr.,Test Netzrelais, ,HW-Fehler,Erdschluss DC,Fehler Messt,Fehler AFI-M,Fehler ST,Fehler DC,Fehler Komm.,Schutzabsch. SW,Schutzabsch. HW, ,Fehler PV-Üb, ,Schneeschmelzen,Netz U Unter L1,Netz U Über L1,Netz U Unter L2,Netz U Über L2,Netz U Unter L3,Netz U Über L3,Netz U Außen,Netz F Unter,Netz F Über,Netz U Mittel,Netz MU UnterL1,Netz MU Über L1,Netz MU UnterL2,Netz MU Über L2,Fehler Zwischen, ,Warte Wiederein,Steuerk. T Über,Fehler Selbstt.,UDC Über,Power-Control,Inselbetrieb,Freq. Reduz.,IAC Max.,Fehler ROCOF,Fehler Plausib."
FehlerCodes[0] = ""
var Verguetung = 5740
var Serialnr =     102505
var Firmware = "2.3.0 Build 32"
var FirmwareDate = "01.02.2011"
var WRTyp = "MULTIPROTOCOL"
var OEMTyp = 0
var SLTyp = " FritzBox"
var SLVer = 2
var SLHW = 2557
var SLBV = 22
var Intervall = 300
var SLDatum = "24.02.12"
var SLUhrzeit = "14:59:52"
var isTemp=true
var isOnline=true
var eventsHP=1
var exportDir=""
var Lang="DE"
var AnzahlGrp=0
var CFDatum = "24.02.12"
var CFUhrzeit = "14:24:27"
var SCB = false
var IPlatform = 3
var DateFormat ="dd.mm.yy"
var TimeFormat ="HH:MM:ss"
var TimeFormatNoSec ="HH:MM"
var Currency ="€"
var CurrencySub ="Cent"
var CurrencyFirst ="0"
var ISOCode ="DE"
var DSTMode ="1"
