var Boot=99
var AnlagenKWP=500
var time_start = new Array(0,0,0,0,0,0,0,0,0,0,0,0)
var time_end = new Array(24,24,24,24,24,24,24,24,24,24,24,24)
var sollMonth = new Array(10,10,10,10,10,10,10,10,10,10,10,10)
var SollYearKWP=100
var AnzahlWR = 3
var MaxWRP=new Array(AnzahlWR)
MaxWRP[0]=new Array(1500,6000,145000,850000)
MaxWRP[1]=new Array(1500,6000,145000,850000)
MaxWRP[2]=new Array(1500,6000,145000,850000)
var WRInfo = new Array(AnzahlWR)
WRInfo[0]=new Array("Phase 1","         1",10000,1,"P1",1,null,null,0,null,2,0,1,1000,null)
WRInfo[1]=new Array("Phase 2","         2",10000,1,"P2",1,null,null,0,null,2,0,1,1000,null)
WRInfo[2]=new Array("Phase 3","         3",10000,1,"P3",1,null,null,0,null,2,0,1,1000,null)
var HPTitel="Verbrauch"
var HPBetreiber="Gisela und Christof Warlich"
var HPEmail="christof@warlich.name"
var HPStandort="Haselhang 7"
var HPModul=""
var HPWR=""
var HPLeistung="4,5kWp"
var HPInbetrieb="25.08.1998"
var HPAusricht=""
var BannerZeile1="Verbrauch"
var BannerZeile2="am Haselhang"
var BannerZeile3="im Netz seit August 2004"
var BannerLink="warlich.bplaced.net/Haselhang-"
var StatusCodes = new Array(AnzahlWR)
var FehlerCodes = new Array(AnzahlWR)
StatusCodes[0] = "Erst.Einsch.,Warte Spannung,Warte Ausschlt,Konstantspann.,MPP Low,MPP,Warten,Warten,Relaistest,Fehlersuchbetr,‹bertemp.Absc,Leistungsbegr,‹berlastabsch,‹berspannab,Netzausfall,Nachtabschalt,Betriebshemm., ,AFI Abschalt.,Iso zu gering, , , , ,Fehler DSP,Test L-Elektr.,Test Netzrelais, ,HW-Fehler,Erdschluss DC,Fehler Messt,Fehler AFI-M,Fehler ST,Fehler DC,Fehler Komm.,Schutzabsch. SW,Schutzabsch. HW, ,Fehler PV-‹b, ,Schneeschmelzen,Netz U Unter L1,Netz U ‹ber L1,Netz U Unter L2,Netz U ‹ber L2,Netz U Unter L3,Netz U ‹ber L3,Netz U Auﬂen,Netz F Unter,Netz F ‹ber,Netz U Mittel,Netz MU UnterL1,Netz MU ‹ber L1,Netz MU UnterL2,Netz MU ‹ber L2,Fehler Zwischen, ,Warte Wiederein,Steuerk. T ‹ber,Fehler Selbstt.,UDC ‹ber,Power-Control,Inselbetrieb,Freq. Reduz.,IAC Max.,Fehler ROCOF,Fehler Plausib."
FehlerCodes[0] = ""
StatusCodes[1] = "Erst.Einsch.,Warte Spannung,Warte Ausschlt,Konstantspann.,MPP Low,MPP,Warten,Warten,Relaistest,Fehlersuchbetr,‹bertemp.Absc,Leistungsbegr,‹berlastabsch,‹berspannab,Netzausfall,Nachtabschalt,Betriebshemm., ,AFI Abschalt.,Iso zu gering, , , , ,Fehler DSP,Test L-Elektr.,Test Netzrelais, ,HW-Fehler,Erdschluss DC,Fehler Messt,Fehler AFI-M,Fehler ST,Fehler DC,Fehler Komm.,Schutzabsch. SW,Schutzabsch. HW, ,Fehler PV-‹b, ,Schneeschmelzen,Netz U Unter L1,Netz U ‹ber L1,Netz U Unter L2,Netz U ‹ber L2,Netz U Unter L3,Netz U ‹ber L3,Netz U Auﬂen,Netz F Unter,Netz F ‹ber,Netz U Mittel,Netz MU UnterL1,Netz MU ‹ber L1,Netz MU UnterL2,Netz MU ‹ber L2,Fehler Zwischen, ,Warte Wiederein,Steuerk. T ‹ber,Fehler Selbstt.,UDC ‹ber,Power-Control,Inselbetrieb,Freq. Reduz.,IAC Max.,Fehler ROCOF,Fehler Plausib."
FehlerCodes[1] = ""
StatusCodes[2] = "Erst.Einsch.,Warte Spannung,Warte Ausschlt,Konstantspann.,MPP Low,MPP,Warten,Warten,Relaistest,Fehlersuchbetr,‹bertemp.Absc,Leistungsbegr,‹berlastabsch,‹berspannab,Netzausfall,Nachtabschalt,Betriebshemm., ,AFI Abschalt.,Iso zu gering, , , , ,Fehler DSP,Test L-Elektr.,Test Netzrelais, ,HW-Fehler,Erdschluss DC,Fehler Messt,Fehler AFI-M,Fehler ST,Fehler DC,Fehler Komm.,Schutzabsch. SW,Schutzabsch. HW, ,Fehler PV-‹b, ,Schneeschmelzen,Netz U Unter L1,Netz U ‹ber L1,Netz U Unter L2,Netz U ‹ber L2,Netz U Unter L3,Netz U ‹ber L3,Netz U Auﬂen,Netz F Unter,Netz F ‹ber,Netz U Mittel,Netz MU UnterL1,Netz MU ‹ber L1,Netz MU UnterL2,Netz MU ‹ber L2,Fehler Zwischen, ,Warte Wiederein,Steuerk. T ‹ber,Fehler Selbstt.,UDC ‹ber,Power-Control,Inselbetrieb,Freq. Reduz.,IAC Max.,Fehler ROCOF,Fehler Plausib."
FehlerCodes[2] = ""
var Verguetung = 2300
var Serialnr =     102505
var Firmware = "2.3.0 Build 32"
var FirmwareDate = "01.02.2011"
var WRTyp = "MULTIPROTOCOL"
var OEMTyp = 0
var SLTyp = " FritzBox"
var SLVer = 2
var SLHW = 2557
var SLBV = 22
var Intervall = 300
var SLDatum = "24.02.12"
var SLUhrzeit = "14:59:52"
var isTemp=true
var isOnline=true
var eventsHP=1
var exportDir=""
var Lang="DE"
var AnzahlGrp=0
var CFDatum = "24.02.12"
var CFUhrzeit = "14:24:27"
var SCB = false
var IPlatform = 3
var DateFormat ="dd.mm.yy"
var TimeFormat ="HH:MM:ss"
var TimeFormatNoSec ="HH:MM"
var Currency ="Ä"
var CurrencySub ="Cent"
var CurrencyFirst ="0"
var ISOCode ="DE"
var DSTMode ="1"
